// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyRewrite(arg1:string):Promise<void>;

export function ApplyRewriteAndPaste(arg1:string):Promise<void>;

export function GetCursorPosition():Promise<Record<string, number>>;

export function Quit():Promise<void>;
