// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {rewriter} from '../models';

export function ApplyRewrite(arg1:string):Promise<void>;

export function ApplyRewriteAndPaste(arg1:string):Promise<void>;

export function DeleteCustomPrompt(arg1:string,arg2:string):Promise<void>;

export function DetectTextType(arg1:string):Promise<any>;

export function GetAllCustomPrompts():Promise<Record<string, Record<string, string>>>;

export function GetAnalysisStyles():Promise<Array<string>>;

export function GetAvailableModels():Promise<Array<string>>;

export function GetCursorPosition():Promise<Record<string, number>>;

export function GetDefaultPrompt(arg1:string,arg2:string):Promise<string>;

export function GetRewriteStyles():Promise<Array<string>>;

export function GetSettings():Promise<config.Config>;

export function GetStyleInfo(arg1:string):Promise<any|boolean>;

export function GetTextTypes():Promise<Array<any>>;

export function Quit():Promise<void>;

export function ResetAllCustomPrompts():Promise<void>;

export function RetryAnalysis(arg1:string,arg2:string):Promise<rewriter.RewriteOption>;

export function RetryAnalysisWithFormatting(arg1:string,arg2:string,arg3:boolean):Promise<rewriter.RewriteOption>;

export function RetryAnalysisWithTextType(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<rewriter.RewriteOption>;

export function RetryRewrite(arg1:string,arg2:string):Promise<rewriter.RewriteOption>;

export function RetryRewriteWithFormatting(arg1:string,arg2:string,arg3:boolean):Promise<rewriter.RewriteOption>;

export function RetryRewriteWithTextType(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<rewriter.RewriteOption>;

export function SaveSettings(arg1:config.Config):Promise<void>;

export function SetCustomPrompt(arg1:string,arg2:string,arg3:string):Promise<void>;

export function TestConnection(arg1:string,arg2:string,arg3:string):Promise<string>;
