// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyRewrite(arg1) {
  return window['go']['main']['App']['ApplyRewrite'](arg1);
}

export function ApplyRewriteAndPaste(arg1) {
  return window['go']['main']['App']['ApplyRewriteAndPaste'](arg1);
}

export function DeleteCustomPrompt(arg1, arg2) {
  return window['go']['main']['App']['DeleteCustomPrompt'](arg1, arg2);
}

export function DetectTextType(arg1) {
  return window['go']['main']['App']['DetectTextType'](arg1);
}

export function GetAllCustomPrompts() {
  return window['go']['main']['App']['GetAllCustomPrompts']();
}

export function GetAnalysisStyles() {
  return window['go']['main']['App']['GetAnalysisStyles']();
}

export function GetAvailableModels() {
  return window['go']['main']['App']['GetAvailableModels']();
}

export function GetCursorPosition() {
  return window['go']['main']['App']['GetCursorPosition']();
}

export function GetDefaultPrompt(arg1, arg2) {
  return window['go']['main']['App']['GetDefaultPrompt'](arg1, arg2);
}

export function GetRewriteStyles() {
  return window['go']['main']['App']['GetRewriteStyles']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStyleInfo(arg1) {
  return window['go']['main']['App']['GetStyleInfo'](arg1);
}

export function GetTextTypes() {
  return window['go']['main']['App']['GetTextTypes']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function ResetAllCustomPrompts() {
  return window['go']['main']['App']['ResetAllCustomPrompts']();
}

export function RetryAnalysis(arg1, arg2) {
  return window['go']['main']['App']['RetryAnalysis'](arg1, arg2);
}

export function RetryAnalysisWithFormatting(arg1, arg2, arg3) {
  return window['go']['main']['App']['RetryAnalysisWithFormatting'](arg1, arg2, arg3);
}

export function RetryAnalysisWithTextType(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RetryAnalysisWithTextType'](arg1, arg2, arg3, arg4);
}

export function RetryRewrite(arg1, arg2) {
  return window['go']['main']['App']['RetryRewrite'](arg1, arg2);
}

export function RetryRewriteWithFormatting(arg1, arg2, arg3) {
  return window['go']['main']['App']['RetryRewriteWithFormatting'](arg1, arg2, arg3);
}

export function RetryRewriteWithTextType(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RetryRewriteWithTextType'](arg1, arg2, arg3, arg4);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SetCustomPrompt(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetCustomPrompt'](arg1, arg2, arg3);
}

export function TestConnection(arg1, arg2, arg3) {
  return window['go']['main']['App']['TestConnection'](arg1, arg2, arg3);
}
