// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyRewrite(arg1) {
  return window['go']['main']['App']['ApplyRewrite'](arg1);
}

export function ApplyRewriteAndPaste(arg1) {
  return window['go']['main']['App']['ApplyRewriteAndPaste'](arg1);
}

export function GetCursorPosition() {
  return window['go']['main']['App']['GetCursorPosition']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}
