// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {rewriter} from '../models';

export function CancelStream(arg1:string):Promise<void>;

export function ComputeDiff(arg1:string,arg2:string):Promise<rewriter.DiffResult>;

export function DeleteCustomPrompt(arg1:string,arg2:string):Promise<void>;

export function DetectTextType(arg1:string):Promise<rewriter.TextTypeDetected>;

export function GetAllCustomPrompts():Promise<Record<string, Record<string, string>>>;

export function GetAnalysisStyles():Promise<Array<string>>;

export function GetDefaultPrompt(arg1:string,arg2:string):Promise<string>;

export function GetRewriteStyles():Promise<Array<string>>;

export function GetStyleInfo(arg1:string):Promise<rewriter.StyleInfoData|boolean>;

export function GetTextTypes():Promise<Array<rewriter.TextTypeInfo>>;

export function ResetAllCustomPrompts():Promise<void>;

export function RetryAnalysis(arg1:string,arg2:string):Promise<rewriter.RewriteOption>;

export function RetryAnalysisWithFormatting(arg1:string,arg2:string,arg3:boolean):Promise<rewriter.RewriteOption>;

export function RetryAnalysisWithTextType(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<rewriter.RewriteOption>;

export function RetryRewrite(arg1:string,arg2:string):Promise<rewriter.RewriteOption>;

export function RetryRewriteWithFormatting(arg1:string,arg2:string,arg3:boolean):Promise<rewriter.RewriteOption>;

export function RetryRewriteWithTextType(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<rewriter.RewriteOption>;

export function SetCustomPrompt(arg1:string,arg2:string,arg3:string):Promise<void>;

export function StreamAnalysisWithTextType(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<void>;

export function StreamRewriteWithFormatting(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function StreamRewriteWithTextType(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<void>;
