// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelStream(arg1) {
  return window['go']['main']['RewriteService']['CancelStream'](arg1);
}

export function ComputeDiff(arg1, arg2) {
  return window['go']['main']['RewriteService']['ComputeDiff'](arg1, arg2);
}

export function DeleteCustomPrompt(arg1, arg2) {
  return window['go']['main']['RewriteService']['DeleteCustomPrompt'](arg1, arg2);
}

export function DetectTextType(arg1) {
  return window['go']['main']['RewriteService']['DetectTextType'](arg1);
}

export function GetAllCustomPrompts() {
  return window['go']['main']['RewriteService']['GetAllCustomPrompts']();
}

export function GetAnalysisStyles() {
  return window['go']['main']['RewriteService']['GetAnalysisStyles']();
}

export function GetDefaultPrompt(arg1, arg2) {
  return window['go']['main']['RewriteService']['GetDefaultPrompt'](arg1, arg2);
}

export function GetRewriteStyles() {
  return window['go']['main']['RewriteService']['GetRewriteStyles']();
}

export function GetStyleInfo(arg1) {
  return window['go']['main']['RewriteService']['GetStyleInfo'](arg1);
}

export function GetTextTypes() {
  return window['go']['main']['RewriteService']['GetTextTypes']();
}

export function ResetAllCustomPrompts() {
  return window['go']['main']['RewriteService']['ResetAllCustomPrompts']();
}

export function RetryAnalysis(arg1, arg2) {
  return window['go']['main']['RewriteService']['RetryAnalysis'](arg1, arg2);
}

export function RetryAnalysisWithFormatting(arg1, arg2, arg3) {
  return window['go']['main']['RewriteService']['RetryAnalysisWithFormatting'](arg1, arg2, arg3);
}

export function RetryAnalysisWithTextType(arg1, arg2, arg3, arg4) {
  return window['go']['main']['RewriteService']['RetryAnalysisWithTextType'](arg1, arg2, arg3, arg4);
}

export function RetryRewrite(arg1, arg2) {
  return window['go']['main']['RewriteService']['RetryRewrite'](arg1, arg2);
}

export function RetryRewriteWithFormatting(arg1, arg2, arg3) {
  return window['go']['main']['RewriteService']['RetryRewriteWithFormatting'](arg1, arg2, arg3);
}

export function RetryRewriteWithTextType(arg1, arg2, arg3, arg4) {
  return window['go']['main']['RewriteService']['RetryRewriteWithTextType'](arg1, arg2, arg3, arg4);
}

export function SetCustomPrompt(arg1, arg2, arg3) {
  return window['go']['main']['RewriteService']['SetCustomPrompt'](arg1, arg2, arg3);
}

export function StreamAnalysisWithTextType(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['RewriteService']['StreamAnalysisWithTextType'](arg1, arg2, arg3, arg4, arg5);
}

export function StreamRewriteWithFormatting(arg1, arg2, arg3, arg4) {
  return window['go']['main']['RewriteService']['StreamRewriteWithFormatting'](arg1, arg2, arg3, arg4);
}

export function StreamRewriteWithTextType(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['RewriteService']['StreamRewriteWithTextType'](arg1, arg2, arg3, arg4, arg5);
}
