// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {engine} from '../models';
import {config} from '../models';

export function CancelAutoDownload():Promise<void>;

export function CheckSetupStatus():Promise<engine.SetupStatus>;

export function GetAvailableModels():Promise<Array<string>>;

export function GetEngineStatus():Promise<engine.Status>;

export function GetSettings():Promise<config.Config>;

export function OpenEngineFolder():Promise<void>;

export function OpenModelsFolder():Promise<void>;

export function SaveSettings(arg1:config.Config):Promise<void>;

export function StartAutoDownload():Promise<void>;

export function StartEmbeddedEngine():Promise<void>;

export function StopEmbeddedEngine():Promise<void>;

export function TestConnection(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<string>;
