// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAvailableModels() {
  return window['go']['main']['SettingsService']['GetAvailableModels']();
}

export function GetSettings() {
  return window['go']['main']['SettingsService']['GetSettings']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['SettingsService']['SaveSettings'](arg1);
}

export function TestConnection(arg1, arg2, arg3, arg4) {
  return window['go']['main']['SettingsService']['TestConnection'](arg1, arg2, arg3, arg4);
}
