// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelAutoDownload() {
  return window['go']['main']['SettingsService']['CancelAutoDownload']();
}

export function CheckSetupStatus() {
  return window['go']['main']['SettingsService']['CheckSetupStatus']();
}

export function GetAvailableModels() {
  return window['go']['main']['SettingsService']['GetAvailableModels']();
}

export function GetEngineStatus() {
  return window['go']['main']['SettingsService']['GetEngineStatus']();
}

export function GetSettings() {
  return window['go']['main']['SettingsService']['GetSettings']();
}

export function OpenEngineFolder() {
  return window['go']['main']['SettingsService']['OpenEngineFolder']();
}

export function OpenModelsFolder() {
  return window['go']['main']['SettingsService']['OpenModelsFolder']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['SettingsService']['SaveSettings'](arg1);
}

export function StartAutoDownload() {
  return window['go']['main']['SettingsService']['StartAutoDownload']();
}

export function StartEmbeddedEngine() {
  return window['go']['main']['SettingsService']['StartEmbeddedEngine']();
}

export function StopEmbeddedEngine() {
  return window['go']['main']['SettingsService']['StopEmbeddedEngine']();
}

export function TestConnection(arg1, arg2, arg3, arg4) {
  return window['go']['main']['SettingsService']['TestConnection'](arg1, arg2, arg3, arg4);
}
