// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadAndInstallUpdate():Promise<void>;

export function SkipUpdate():Promise<void>;
