// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadAndInstallUpdate() {
  return window['go']['main']['UpdateService']['DownloadAndInstallUpdate']();
}

export function SkipUpdate() {
  return window['go']['main']['UpdateService']['SkipUpdate']();
}
